services:
  - type: web
    name: seaweed-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn python.server:app --host 0.0.0.0 --port 8000"
    plan: free
